"""Export every BP_DoorMarker placed in the open level to a nanos world Lua file.

The nanos world server doesn't run Unreal, so doors placed in a map only
exist on clients. This editor-only script turns the placed markers into a
MapDoors.lua that the map package's server script requires; it calls
BaseDoor.SpawnFromList() from the `door` package to spawn real,
server-authoritative doors at the same spots.

Run it in the Unreal Editor with the level open:
    Tools > Execute Python Script... > export_doors.py
(needs the "Python Editor Script Plugin", enabled by default in UE 5.7).
"""

import datetime
import os

import unreal

# Any placed actor whose Blueprint class name starts with this is exported
# (so child Blueprints like BP_DoorMarker_Metal are picked up too).
MARKER_CLASS_PREFIX = "BP_DoorMarker"

# Where to write the Lua file. Leave empty to write to
# <Project>/Saved/NanosDoor/<LevelName>_MapDoors.lua, or point it straight at
# your map package, eg. r"E:\...\Packages\my-map\Server\MapDoors.lua".
OUTPUT_PATH = ""


def _snake_case(name):
    out = []
    for i, char in enumerate(name):
        if char.isupper() and i > 0:
            out.append("_")
        out.append(char.lower())
    return "".join(out)


def _get(actor, name, default=None):
    # Blueprint variables are reachable by their exact name; snake_case is
    # tried too since Python-exposed property names are sometimes converted.
    for candidate in (name, _snake_case(name)):
        try:
            return actor.get_editor_property(candidate)
        except Exception:
            pass
    return default


def _num(value):
    text = "{:.3f}".format(value).rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def _lua_string(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _lua_vector(vector):
    return "Vector({}, {}, {})".format(_num(vector.x), _num(vector.y), _num(vector.z))


def _lua_rotator(rotator):
    # nanos world's Rotator takes (pitch, yaw, roll).
    return "Rotator({}, {}, {})".format(_num(rotator.pitch), _num(rotator.yaw), _num(rotator.roll))


def _is_zero(vector):
    return vector is None or (vector.x == 0 and vector.y == 0 and vector.z == 0)


def _door_spec(actor):
    fields = [
        "type = " + _lua_string(_get(actor, "DoorType", "Hinge") or "Hinge"),
        "location = " + _lua_vector(actor.get_actor_location()),
        "rotation = " + _lua_rotator(actor.get_actor_rotation()),
        "mode = " + _lua_string("interact" if _get(actor, "Interactable", False) else "trigger"),
    ]

    asset = str(_get(actor, "DoorAsset", "") or "")
    if asset:
        fields.append("asset = " + _lua_string(asset))

    scale = _get(actor, "DoorScale")
    if not _is_zero(scale):
        fields.append("scale = " + _lua_vector(scale))

    slide_offset = _get(actor, "SlideOffset")
    if not _is_zero(slide_offset):
        fields.append("slide_offset = " + _lua_vector(slide_offset))

    if _get(actor, "StartLocked", False):
        fields.append("locked = true")

    return "    {{ {} }}, -- {}".format(", ".join(fields), actor.get_actor_label())


def main():
    world = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
    level_name = world.get_name()

    actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem).get_all_level_actors()
    markers = [a for a in actors if a.get_class().get_name().startswith(MARKER_CLASS_PREFIX)]
    # Stable order so re-exporting an unchanged map produces an identical file.
    markers.sort(key=lambda a: a.get_actor_label())

    lines = [
        "-- Generated by Nanos_Door_UE/Scripts/export_doors.py from level '{}' on {}.".format(
            level_name, datetime.datetime.now().strftime("%Y-%m-%d %H:%M")),
        "-- Do not edit by hand: move the BP_DoorMarker actors in Unreal and re-export.",
        "-- Requires the `door` package (list it in packages_requirements).",
        "return BaseDoor.SpawnFromList({",
    ]
    lines += [_door_spec(actor) for actor in markers]
    lines.append("})")

    output = OUTPUT_PATH or os.path.join(
        unreal.Paths.project_saved_dir(), "NanosDoor", level_name + "_MapDoors.lua")
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(lines) + "\n")

    unreal.log("[NanosDoor] Exported {} door(s) from '{}' to {}".format(len(markers), level_name, output))
    if not markers:
        unreal.log_warning("[NanosDoor] No actor whose class starts with '{}' found in the level.".format(
            MARKER_CLASS_PREFIX))


main()
